### PR TITLE
Revert a commit with data.loaders (fix #10)

### LINKED ISSUE #10: Broken jquery
```
webpack src/index.js assets/bundle.js
-------
module.exports = require("./dist/jquery.js");
-------
Hash: e66002ae5e5c3fd56461
Version: webpack 1.4.15
Time: 1644ms
    Asset    Size  Chunks             Chunk Names
bundle.js  615622       0  [emitted]  main
  [10] jquery (bower component) -1 [built] [failed]
    + 165 hidden modules

ERROR in jquery (bower component)
Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (/Users/hh-webpack/node_modules/json-loader/index.js:10:19)
 @ ./index.js 1:8-25
```

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
We should not support custom loaders for manifest main files

### CODE REVIEW

**Comment by lpiepiora** [comment]
@DenisIzmaylov thanks for your contribution, would it be possible to create a test case, which reproduces this issue, so we can avoid this situation in the future?

Or maybe you could tell me how can I reproduce it, so I can write a test case?

**Comment by mdreizin** [comment]
@lpiepiora This PR breaks some modules which defined in config under `module.loaders` section, for instance https://www.npmjs.com/package/json-loader.

```
module: {
        loaders: [{
            test: /\.json$/,
            loader: 'json-loader'
        }]
    }
```

**Comment by lpiepiora** [comment]
@mdreizin do you mean this PR (that is https://github.com/DenisIzmaylov/bower-webpack-plugin/commit/4bd85f9651b4988cc3434257f1188d1bca5d43e4) or the commit that this PR reverts?

**Comment by mdreizin** [comment]
@lpiepiora The following PR #9.

**Comment by lpiepiora** [comment]
@mdreizin so you're in favour of merging PR made by @DenisIzmaylov, correct ?

**Comment by mdreizin** [comment]
@lpiepiora we've looked deeper into this issue and found out that it's not likely to be an issue of this plugin and PR #9. For some reason, when `json-loader` is used together with `bower-webpack-plugin`, the latter retrieves it not directly, but via that loader, which causes an error for each bower package referenced. A temporary fix is to exclude `bower.json` from `json-loader` configuration, but a proper way to fix it would be to examine `webpack` core logic on that matter.

**Comment by lpiepiora** [comment]
@mdreizin I see, thanks for the information. Would you be able by a chance to provide self contained example of such a situation, so I can easily run it on my side?

**Comment by mdreizin** [comment]
@lpiepiora please see https://github.com/mdreizin/playground/tree/master/bower-webpack-plugin/issues/11

**Comment by lpiepiora** [comment]
@mdreizin I looked at your project with the issue (sorry it took this long). I guess indeed this PR will fix it. The change the PR is recommending is `data.loaders = [bowerLoaderPath + "?" + bowerLoaderParams]`, which is good, because the other PR changed this to `data.loaders.concat(bowerLoaderPath + "?" + bowerLoaderParams)`, which I think was asking webpack to load the resource (`bower.json` file). This is not what we want, because when the file is resolved we want to use our own resolver to load it, as it actually parses it and loads the dependencies.

I'll merge this PR in seconds, and then release a fixed version. Let me know if you'll still need your workaround (tested with your project, and there it seems to be fine).

**Comment by mdreizin** [comment]
@lpiepiora Now it works fine. Thanks a lot!

**Pull request merged**
